[versions]
coroutines = "1.8.1-Beta"
detekt = "1.23.6"
gradleVersionsPlugin = "0.51.0"
jetbrainsCompose = "1.6.10-beta02"
jetbrainsComposeCompiler = "1.5.11-kt-2.0.0-RC1"
kotlin = "2.0.0-RC1"
webpack = "5.91.0"
webpackCli = "5.1.4"
webpackDevServer = "5.0.4"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }