[versions]
coroutines = "1.8.0"
detekt = "1.23.5"
gradleVersionsPlugin = "0.51.0"
jetbrainsCompose = "1.6.0-rc02"
jetbrainsComposeCompiler = "1.5.4-dev1-kt2.0.0-Beta1"
kotlin = "2.0.0-Beta1"
webpack = "5.76.0"
webpackCli = "5.1.1"
webpackDevServer = "4.15.0"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }