[versions]
composeCompiler = "1.4.8-dev-k1.9.0-RC-5532d15c918"
detekt = "1.23.0"
gradleVersionsPlugin = "0.47.0"
jetbrainsCompose = "1.5.0-dev1084"
kotlin = "1.9.0-RC"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }