name: Check and Build
on:
  push:
    branches:
      - develop
      - renovate/**
  pull_request:
    branches:
      - develop
      - main

jobs:
  detekt:
    name: Run detekt & ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run detekt with ktlint
        run: ./gradlew detekt ktlintCheck

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test and Build
        run: ./gradlew build
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4