name: Check and Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  detekt:
    name: Run detekt & ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Run detekt with ktlint
        run: ./gradlew detekt ktlintCheck

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Test and Build
        run: ./gradlew build